source 'https://rubygems.org'

gem 'heroku'
gem 'sinatra', '>= 4.2.0'
gem 'sinatra-sprockets'
gem 'sinatra-contrib', '>= 4.2.0'
gem 'sprockets-sass'
gem 'coffee-script'
gem 'haml_coffee_assets', '>= 1.9.1'
gem 'koala'
gem 'haml'
gem 'sass'
gem 'thin', '>= 1.5.1'
gem 'shotgun', '>= 0.9.1'
gem 'sinatra-partial', '>= 0.4.0'