source 'https://rubygems.org'

gem 'heroku', '>= 3.99.4'
gem 'sinatra', '>= 2.2.3'
gem 'sinatra-sprockets'
gem 'sinatra-contrib', '>= 2.2.3'
gem 'sprockets-sass'
gem 'coffee-script'
gem 'haml_coffee_assets'
gem 'koala'
gem 'haml', '>= 5.0.0'
gem 'sass'
gem 'thin'
gem 'shotgun'
gem 'sinatra-partial'